`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////
// Module: fast_inv_sqrt_top
//
// Top-level pipelined Fast Inverse Square Root (Quake III style).
//
// Total pipeline latency: 11 clock cycles
//   - Stage 0 (1 clk): magic_number_approx + float_divide_by_two
//   - Stages 1-10 (10 clk): newton_raphson_stage (3 + 4 + 3)
//
// data_valid goes high 11 cycles after the first valid data_in,
// generated by an 11-stage shift register fed with a constant 1.
//////////////////////////////////////////////////////////////////////////////

module fast_inv_sqrt_top (
    input  wire        clk,
    input  wire [31:0] data_in,
    output wire [31:0] data_out,
    output wire        data_valid
);

    // -----------------------------------------------------------------------
    // Stage 0: Initial approximation + x/2
    // -----------------------------------------------------------------------
    wire [31:0] y_approx;
    wire [31:0] x2_approx;

    magic_number_approx u_magic (
        .clk   (clk),
        .x     (data_in),
        .y_out (y_approx)
    );

    float_divide_by_two u_half (
        .clk    (clk),
        .x      (data_in),
        .x2_out (x2_approx)
    );

    // -----------------------------------------------------------------------
    // Stages 1-10: Newton-Raphson refinement
    // -----------------------------------------------------------------------
    wire        nr_valid;

    newton_raphson_stage u_newton (
        .clk        (clk),
        .y_in       (y_approx),
        .x2_in      (x2_approx),
        .final_out  (data_out),
        .final_valid (nr_valid)
    );

    // -----------------------------------------------------------------------
    // data_valid generation: 11-stage shift register
    // A constant 1'b1 is fed into stage 0 every cycle.
    // After 11 rising edges the '1' propagates to the output.
    // -----------------------------------------------------------------------
    reg [10:0] valid_sr = 11'b0;   // initialised to all zeros
    integer i;

    always @(posedge clk) begin
        valid_sr[0] <= 1'b1;
        for (i = 1; i < 11; i = i + 1) begin
            valid_sr[i] <= valid_sr[i-1];
        end
    end

    assign data_valid = valid_sr[10];

endmodule
